site:
  host: https://tcprodojo.com

paths:
  static:
    - assets

collections_config:
  blog:
    path: blog
    output: true
    _enabled_editors: [content, visual]
    _name_key: title
    create:
      path: "blog/{slug}.md"
    schema:
      fields:
        - type: text
          name: title
          label: Title
        - type: datetime
          name: date
          label: Publish Date
        - type: markdown
          name: body
          label: Body

_editables:
  - path: index.html
    selectors:
      - "h1"                # hero title
      - "p"                 # hero paragraph (first section)
      - "a[href*='tryout']" # CTA button text
      - ".nav a"            # menu labels (optional)
