backend:
  name: github
  repo: swilsonify/tcprodojo-site
  branch: main
  base_url: https://cozy-sundae-3daf54.netlify.app
  auth_endpoint: /.netlify/functions/auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
